# Generated by Django 4.0.6 on 2022-12-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='approved_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.CharField(max_length=255)),
                ('driver', models.CharField(max_length=255)),
                ('passenger', models.CharField(max_length=255)),
                ('current_area', models.CharField(max_length=255)),
                ('current_stop', models.CharField(max_length=255)),
                ('destination_area', models.CharField(max_length=255)),
                ('destination_stop', models.CharField(max_length=255)),
                ('d_date', models.CharField(max_length=255)),
                ('d_time', models.CharField(max_length=255)),
                ('number_of_people', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='denied_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.CharField(max_length=255)),
                ('driver', models.CharField(max_length=255)),
                ('passenger', models.CharField(max_length=255)),
                ('current_area', models.CharField(max_length=255)),
                ('current_stop', models.CharField(max_length=255)),
                ('destination_area', models.CharField(max_length=255)),
                ('destination_stop', models.CharField(max_length=255)),
                ('d_date', models.CharField(max_length=255)),
                ('d_time', models.CharField(max_length=255)),
                ('number_of_people', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ride_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.CharField(max_length=255)),
                ('driver', models.CharField(max_length=255)),
                ('passenger', models.CharField(max_length=255)),
                ('current_area', models.CharField(max_length=255)),
                ('current_stop', models.CharField(max_length=255)),
                ('destination_area', models.CharField(max_length=255)),
                ('destination_stop', models.CharField(max_length=255)),
                ('d_date', models.CharField(max_length=255)),
                ('d_time', models.CharField(max_length=255)),
                ('number_of_people', models.CharField(max_length=255)),
            ],
        ),
    ]
