# Generated by Django 4.0.6 on 2022-11-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivers',
            name='phonenumber',
        ),
    ]
