# Generated by Django 4.0.6 on 2022-11-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_drivers_phonenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drivers',
            new_name='Create_Driver',
        ),
        migrations.RenameField(
            model_name='create_driver',
            old_name='password1',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='create_driver',
            old_name='password2',
            new_name='phonenumber',
        ),
    ]
